name: Mercury docker build and push

on:
  push:
    branches:
      - 'master'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Registry
        uses: docker/login-action@v1 
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: List files in path
        run: echo $(ls -a)
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Clone mercury repository
        uses: actions/checkout@master
        with:
          repository: mercury-app/mercury
          token: ${{ secrets.MY_PAT }}
          with:
            path: 'mercury'
      - 
        name: List files in path
        run: echo $(ls -a) && echo $(pwd)
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: mercury:latest
          path: 
      # -
      #   name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}